name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.7.3
      - name: Install dependencies
        run: bundle install
        shell: bash
      - name: Rubocop Linting
        run: rubocop
        shell: bash
      - name: Run tests
        run: bundle exec rake
        shell: bash
      - name: Upload Test Coverage
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b
        with:
          directory: ./coverage